---
- name: Instalar Apache
  apt:
    name: apache2
    state: present
- name: Copiar archivo index.html
  copy:
    src: index.html
    dest: /var/www/html/index.html
    mode: '0644'
- name: Reiniciar Apache
  service:
    name: apache2
    state: restarted
